exports.config = {
    host: "localhost",
    port: 4444,
    path: "/wd/hub",
    specs: ["./specs/**/*.js"],
    exclude: ["./specs/helpers/**/*.js"],
    maxInstances: 10,
    capabilities: [{
        browserName: "chrome",
        "goog:chromeOptions": {args: ["headless", "disable-gpu", "window-size=1280,800", "no-sandbox"]},
        excludeDriverLogs: ['server'],
    }],
    logLevel: "silent",
    coloredLogs: true,
    bail: 0,
    screenshotPath: "./errorShots/",
    baseUrl: `http://localhost:8001`,
    waitforTimeout: 1000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: [[
        "selenium-standalone",
        {drivers: {chrome: true}},
    ]],
    framework: "mocha",
    reporters: ["spec"],
    mochaOpts: {ui: "bdd"},
}
