name: tests
run-name: testing
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
        
    steps:
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: beta
      - run: elm make src/ScalarSetTheory/Main.elm --output dist/index.html
      - run: npm i -g elm-test
      - run: elm-test init
      - run: rm tests/Example.elm
      - run: elm-test
      - run: cd integration-tests && npm i
      - run: elm reactor --port 8001 &
      - run: cd integration-tests && npm t
